apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
        - name: loans
          image: cristixndr3s/app-microservicios-loans:v1
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: CONFIG_SERVER_URL

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: EUREKA_SERVER_URL

