pipeline {
    agent any

    environment {
        IMAGE_NAME = "cristixndr3s/app-microservicios-loans"
        CREDENTIALS_ID = "dockerhub-credentials"
    }

    stages {
        stage('Build Maven') {
            steps {
                dir('loans') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:v1", 'loans/')
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${CREDENTIALS_ID}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    sh "docker push ${IMAGE_NAME}:v1"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/loans-deployment.yaml'
            }
        }
    }
}
