apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  CONFIG_SERVER_URL: "http://configserver-service:8071/"
  EUREKA_SERVER_URL: "http://eurekaserver-service:8070/eureka/"
