apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: cristixndr3s/app-microservicios-configserver:v1
          ports:
            - containerPort: 8071


